# Generated by Django 4.1.7 on 2024-08-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("brand", models.CharField(max_length=50)),
                ("num", models.IntegerField()),
                ("description", models.FileField(upload_to="product_description/")),
                (
                    "skill_lv",
                    models.CharField(
                        choices=[
                            ("beginner", "初學者"),
                            ("intermediate", "中級"),
                            ("advanced", "高級"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProuctAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment", models.CharField(max_length=100)),
                ("audio", models.FileField(upload_to="product_audio/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_samples",
                        to="back.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="product_img/")),
                ("primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="img",
                        to="back.product",
                    ),
                ),
            ],
        ),
    ]
