# Generated by Django 4.1.7 on 2024-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.FileField(upload_to="media/product_description/"),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="img",
            field=models.ImageField(upload_to="media//product_img/"),
        ),
        migrations.AlterField(
            model_name="prouctaudio",
            name="audio",
            field=models.FileField(upload_to="media//product_audio/"),
        ),
    ]
