# Generated by Django 4.1.7 on 2024-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0002_alter_product_description_alter_productimg_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="img",
            field=models.ImageField(upload_to="media/product_img/"),
        ),
    ]
