# Generated by Django 4.1.7 on 2024-08-05 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0003_alter_productimg_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProuctAudio",
            new_name="ProductAudio",
        ),
    ]
