# Generated by Django 4.1.7 on 2024-08-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0004_rename_prouctaudio_productaudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Electric Guitar"),
                    (2, "Amplifier"),
                    (3, "Effects Pedal"),
                    (4, "Gig Bag"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productaudio",
            name="audio",
            field=models.FileField(upload_to="media/product_audio/"),
        ),
    ]
