# Generated by Django 4.1.7 on 2024-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0008_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.FileField(
                blank=True, null=True, upload_to="media/product_description/"
            ),
        ),
        migrations.AlterField(
            model_name="productaudio",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="media/product_audio/"
            ),
        ),
        migrations.AlterField(
            model_name="productaudio",
            name="equipment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
