# Generated by Django 4.1.7 on 2024-09-21 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0009_alter_product_description_alter_productaudio_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
