# Generated by Django 4.1.7 on 2024-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0010_alter_order_is_send_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
